[project_vms]
vm1 ansible_host=192.168.56.11 ansible_ssh_private_key_file=./vm1_key
vm2 ansible_host=192.168.56.12 ansible_ssh_private_key_file=./vm2_key
vm3 ansible_host=192.168.56.13 ansible_ssh_private_key_file=./vm3_key

[project_vms:vars]
ansible_user=vagrant
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
